### ISSUE TITLE
Hello, can you provide the above files ? smpl_model

### ISSUE THREAD

**Issue by guilh98** [z3y50n/SmartMirror#7]
widgets/exercisor/model_cfg.py

model_dir = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "pretrained_models_data"
)
pretrained_path = os.path.join(model_dir, "model.ckpt-667589")
smpl_model_path = os.path.join(model_dir, "neutral_smpl_with_cocoplus_reg.pkl")
smpl_faces_path = os.path.join(model_dir, "smpl_faces.npy")

Hello, can you provide the above files

**Comment by z3y50n** [comment]
@FilipposZ

**Comment by guilh98** [comment]
Thank you very much.
